name: on-release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
          cache: npm
          scope: "@jravas"

      - name: Install dependencies
        run: npm ci

      - name: Build Application
        run: |
          npm run build

      - name: Publish Application
        working-directory: ./dist/uselesser
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
