name: on-release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Application
        run: |
          yarn build

      - name: Build site assets and
        working-directory: ./dist/uselesser
        run: ls -la

      - name: Publish Application
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
